[package]
name = "tvis"
version = "0.10.1"
authors = ["Ed McCardell <edmccard@hotmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/edmccard/tvis"
description = """
A console/terminal UI library (very alpha! such WIP!)
"""

[dependencies]
tinf = { path = "../tinf", version = "0.10.0" }

[badges]
travis-ci = { repository = "edmccard/tvis" }
