[package]
name = "tinf"
version = "0.10.0"
authors = ["Ed McCardell <edmccard@hotmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/edmccard/tvis"
description = """
A library for using terminfo capabilities.
"""

[badges]
travis-ci = { repository = "edmccard/tvis" }
